config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}
  #d6ebafe3f185ba281860005067fa742a
root to: "tops#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'tops/index' => 'tops#index'
get 'posts/new' => 'posts#new'
post 'posts/new' => 'posts#create'
get 'posts/index' => 'posts#index'
get 'users/search' => 'users#search'
get 'lookups' => 'lookups#index'
post 'lookups' => 'lookups#index'
resources :posts do
  resources :comments
end
resources :profiles, only: [:create,:update]
get 'posts/:id' => 'posts#show'
get 'users/:id' => 'users#show'

resources :users do
    member do
     get :following, :followers
    end
  end

resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #d6ebafe3f185ba281860005067fa742a
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_one:profile
  has_many:posts
  has_many:comments
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        facebook_image:  auth.info.image
      )
    end

    user
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def image_show
    if self.profile.persisted? && self.profile.image?
      self.profile.image.to_s
    elsif !self.facebook_image.nil?
      self.facebook_image.to_s
    else
      "/assets/no_avatar.png"
    end
  end

  def following?(other_user)
   following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
   following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
   following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    if current_user.profile == nil
      @profile = Profile.new
    else
      @profile = current_user.profile
    end
    super

  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protect_from_forgery except: :update
  protected
  def after_update_path_for(resource)
      users_show_path
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def search
  end

  def detail
    @detail = User.find(params[:id])
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-lg btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
 <% if current_user.following?(@user) %>
   <%= render 'unfollow' %>
 <% else %>
   <%= render 'follow' %>
 <% end %>
 </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-danger follow-btn" %>
<% end %>

app/views/users/detail.html.erb
<div class="user_detail">
 <%= @detail.profile.username %>
</div>

app/views/users/search.html.erb
<div class="user_search">
</div>

app/views/users/show.html.erb
<div class="user_show">
    <div class="mypage">
      <div class="first-block">
        <div class="image">
          <%=image_tag @user.image_show %>
        </div>
        <div class="username">
          <% if @user.profile != nil %>
            <%= @user.profile.username %>
          <% end %>
        </div>
        <div class="to_edit">
          <% if @user == current_user %>
           <%= link_to "Edit Info", edit_user_registration_path, class:"edit_button"%>
          <% else %>
          <div id="follow_form">
             <% if current_user.following?(@user) %>
               <%= render 'unfollow' %>
             <% else %>
               <%= render 'follow' %>
             <% end %>
          </div>
          <% end %>
        </div>
          <% if @user.profile != nil %>
        <div class="nativeLanguage">
          Native:<br><%= @user.profile.nativeLanguage%>
        </div>
        <div class="newLanguage">
          Learn:<br><%= @user.profile.newLanguage%>
        </div>
        <div class="posts">
          Posts<br>45
        </div>
        <div class="following">
          Following<br>
          <a href="<%= following_user_path(@user) %>">
           <strong id="following" class="stat">
             <%= @user.followings.count %>
           </strong>
          </a>
        </div>
        <div class="follower">
          Follower<br>
          <a href="<%= followers_user_path(@user) %>">
            <strong id="followers" class="stat">
              <%= @user.followers.count %>
            </strong>
          </a>
        </div>
      </div>
      <div class="second-block">
        <div class="introduction">
          <%= @user.profile.introduction%>
        </div>
      </div>
      <div class="third-block">
        <h3>User Profile</h3>
        <div class="homeCountry">
        Home Country:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.profile.homeCountry %>
        </div>
        <div class="nativeLanguage">
          Native language:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.profile.nativeLanguage%>
        </div>
        <div class="newLanguage">
          Learning Language:&nbsp;&nbsp;&nbsp;<%= @user.profile.newLanguage%>
        </div>
        <div class="languageLevel">
        Language level:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.profile.languageLevel%>
        </div>
        <div class="age">
        Age:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.profile.age %>
        </div>
        <div class="job">
        Job:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.profile.job%>
        </div>
        <div class="residence">
        Residence:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.profile.residence%>
        </div>
       </div>
      <% end %>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
    </div>
  </div>

app/views/users/show_follow.html.erb
<div class="show_following">
  <h2>Following</h2>
  <% @user.followings.each do |user| %>
  <div class="following_box">
    <div class="following_image">
      <%if user.uid == nil%>
       <%= link_to image_tag("#{user.profile.image}"), user_path(user) %>
      <% else %>
       <%= link_to image_tag("#{user.facebook_image}"), user_path(user) %>
      <% end %>
    </div>
      <%= link_to user.profile.username, user_path(user) %><br>
  </div>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<div class="show_follower">
  <% @user.followers.each do |user| %>
   <div class="follower_image">
     <%if user.uid == nil%>
      <%= link_to image_tag ("#{user.profile.image}"), user_path(user)%>
     <% else %>
      <%= image_tag ("#{user.facebook_image}")%>
     <% end %>
   </div>
     <%= user.profile.username %>
    <%= link_to user.profile.username, user_path(user) %><br>
  <% end %>
</div>