config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}
  #d6ebafe3f185ba281860005067fa742a
root to: "tops#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'tops/index' => 'tops#index'
get 'posts/new' => 'posts#new'
post 'posts/new' => 'posts#create'
get 'posts/index' => 'posts#index'
get 'users/search' => 'users#search'
get 'lookups' => 'lookups#index'
post 'lookups' => 'lookups#index'
resources :posts do
  resources :comments
end
resources :profiles, only: [:create,:update]
get 'posts/:id' => 'posts#show'
get 'users/:id' => 'users#show'

resources :users do
    member do
     get :following, :followers
    end
  end

resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to:user
  belongs_to:post
end

app/models/other.rb
class Other < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
   mount_uploader :image, ImageUploader
   belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many:comments
  belongs_to:user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #d6ebafe3f185ba281860005067fa742a
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_one:profile
  has_many:posts
  has_many:comments
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        facebook_image:  auth.info.image
      )
    end

    user
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def image_show
    if self.profile.persisted? && self.profile.image?
      self.profile.image.to_s
    elsif !self.facebook_image.nil?
      self.facebook_image.to_s
    else
      "/assets/no_avatar.png"
    end
  end

  def following?(other_user)
   following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
   following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
   following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all.order("id DESC")
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    #新しいTweetの保存に成功した場合
    if @post.save
      #index.html.erbにページが移る
      redirect_to action: "index"
    #新しいTweetの保存に失敗した場合
    else
      #もう一回投稿画面へ
      redirect_to action: "new"
    end
   end

 def show
   @post = Post.find(params[:id])
   @comment = Comment.new
   @comments = @post.comments
 end

 private
 #セキュリティのため、許可した:bodyというデータだけ取ってくるようにする
 def post_params
  params.require(:post).permit(:body)
 end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
         <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <%= link_to "Log in", new_user_session_path,class: 'btn btn-default btn-primary btn-lg' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <a class="nav-link" data-toggle="modal" data-target="#signUpModal"><span>Sign Up</span></a>
          </li>
        <% end %>
      </ul>
    </div>
</nav> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <header class="header-all">
        <div class="logo">friendo!</div>
        <div class="link-lists">
         <div class="Home">
            <svg class ="home-icon" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="home" class="svg-inline--fa fa-home fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M280.37 148.26L96 300.11V464a16 16 0 0 0 16 16l112.06-.29a16 16 0 0 0 15.92-16V368a16 16 0 0 1 16-16h64a16 16 0 0 1 16 16v95.64a16 16 0 0 0 16 16.05L464 480a16 16 0 0 0 16-16V300L295.67 148.26a12.19 12.19 0 0 0-15.3 0zM571.6 251.47L488 182.56V44.05a12 12 0 0 0-12-12h-56a12 12 0 0 0-12 12v72.61L318.47 43a48 48 0 0 0-61 0L4.34 251.47a12 12 0 0 0-1.6 16.9l25.5 31A12 12 0 0 0 45.15 301l235.22-193.74a12.19 12.19 0 0 1 15.3 0L530.9 301a12 12 0 0 0 16.9-1.6l25.5-31a12 12 0 0 0-1.7-16.93z"></path></svg>
            <%= link_to "Home", posts_index_path, class:"home-link" %>
         </div>
         <div class="Mypage">
            <svg class ="user-icon" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user" class="svg-inline--fa fa-user fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"></path></svg>
            <%= link_to "My Page",user_path(current_user.id), class:"mypage-link" %>
         </div>
         <div class ="Lookup">
            <svg class="lookup-icon" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="svg-inline--fa fa-search fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg>
            <%= link_to "Find Friends",lookups_path, class:"lookup-link" %>
         </div>
         <div class="Message">
            <svg class="message-icon" aria-hidden="true" focusable="false" data-prefix="far" data-icon="envelope" class="svg-inline--fa fa-envelope fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm0 48v40.805c-22.422 18.259-58.168 46.651-134.587 106.49-16.841 13.247-50.201 45.072-73.413 44.701-23.208.375-56.579-31.459-73.413-44.701C106.18 199.465 70.425 171.067 48 152.805V112h416zM48 400V214.398c22.914 18.251 55.409 43.862 104.938 82.646 21.857 17.205 60.134 55.186 103.062 54.955 42.717.231 80.509-37.199 103.053-54.947 49.528-38.783 82.032-64.401 104.947-82.653V400H48z"></path></svg>
            Message
         </div>
         <div class="Notification">
            <svg class="notification-icon" aria-hidden="true" focusable="false" data-prefix="far" data-icon="bell" class="svg-inline--fa fa-bell fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M439.39 362.29c-19.32-20.76-55.47-51.99-55.47-154.29 0-77.7-54.48-139.9-127.94-155.16V32c0-17.67-14.32-32-31.98-32s-31.98 14.33-31.98 32v20.84C118.56 68.1 64.08 130.3 64.08 208c0 102.3-36.15 133.53-55.47 154.29-6 6.45-8.66 14.16-8.61 21.71.11 16.4 12.98 32 32.1 32h383.8c19.12 0 32-15.6 32.1-32 .05-7.55-2.61-15.27-8.61-21.71zM67.53 368c21.22-27.97 44.42-74.33 44.53-159.42 0-.2-.06-.38-.06-.58 0-61.86 50.14-112 112-112s112 50.14 112 112c0 .2-.06.38-.06.58.11 85.1 23.31 131.46 44.53 159.42H67.53zM224 512c35.32 0 63.97-28.65 63.97-64H160.03c0 35.35 28.65 64 63.97 64z"></path></svg>
             Notification
         </div>
        </div>
      </header>
    <% else %>
      <header class ="header-nav">
        <div class="logo">friendo!</div>
        <div class="nav-list">
          <nav><a href="#first-block">Home</a></nav>
          <nav><a href="#second-block">About</a></nav>
          <nav><a href="#third-block">How to use</a></nav>
          <nav><a href="#fourth-block">Why Friendo?</a></nav>
              <%= link_to "Log in", new_user_session_path,class: 'btn btn-default btn-primary btn-lg' %>
        </div>
     <% end %>

      </header>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <% unless user_signed_in? %>
     <%= render partial: 'devise/registrations/new' %>
    <% end %>
  </body>
</html>